<?php

$demo_menus = array(
	'primary' => 'Main Menu',
	'social' => 'Social Menu'
);

$demo_reading_pages = array(
	'front' => 'Front page — Featured Projects Slider',
	'blog' => 'Journal'
);

/**
 * Use this plugin to export WordPress options https://wordpress.org/plugins/options-importer/
 * Steps:
 * 1 - Export the demo options
 * 2 - From the exported file get only the options array and encode it http://vps5.cgwizz.com/encoder/
 * 3 - After that paste the encoded string here:
 */
$theme_options = "ew0KICAgICJuYXZfbWVudV9vcHRpb25zIjogImE6Mjp7aTowO2I6MDtzOjg6XCJhdXRvX2FkZFwiO2E6MDp7fX0iLA0KICAgICJwb3N0c19wZXJfcGFnZSI6ICIxMCIsDQogICAgInBvc3RzX3Blcl9yc3MiOiAiMTAiLA0KICAgICJ0aGVtZV9tb2RzX3RpbWJlciI6ICJhOjI6e2k6MDtiOjA7czoxODpcIm5hdl9tZW51X2xvY2F0aW9uc1wiO2E6Mjp7czo3OlwicHJpbWFyeVwiO2k6NztzOjY6XCJzb2NpYWxcIjtpOjk7fX0iLA0KICAgICJ0aW1iZXJfb3B0aW9ucyI6ICJhOjI6e3M6MTM6XCJoZWFkaW5nc19mb250XCI7czoxOTI6XCJ7XCJ0eXBlXCI6XCJnb29nbGVcIixcImZvbnRfZmFtaWx5XCI6XCJPc3dhbGRcIixcInZhcmlhbnRzXCI6e1wiMFwiOlwiMzAwXCIsXCIxXCI6XCJyZWd1bGFyXCIsXCIyXCI6XCI3MDBcIn0sXCJzZWxlY3RlZF92YXJpYW50c1wiOntcIjBcIjpcIjMwMFwifSxcInN1YnNldHNcIjp7XCIwXCI6XCJsYXRpblwiLFwiMVwiOlwibGF0aW4tZXh0XCJ9LFwic2VsZWN0ZWRfc3Vic2V0c1wiOntcIjBcIjpcImxhdGluXCJ9fVwiO3M6OTpcImJvZHlfZm9udFwiO3M6Mzk2Olwie1widHlwZVwiOlwiZ29vZ2xlXCIsXCJmb250X2ZhbWlseVwiOlwiUm9ib3RvXCIsXCJ2YXJpYW50c1wiOntcIjBcIjpcIjEwMFwiLFwiMVwiOlwiMTAwaXRhbGljXCIsXCIyXCI6XCIzMDBcIixcIjNcIjpcIjMwMGl0YWxpY1wiLFwiNFwiOlwicmVndWxhclwiLFwiNVwiOlwiaXRhbGljXCIsXCI2XCI6XCI1MDBcIixcIjdcIjpcIjUwMGl0YWxpY1wiLFwiOFwiOlwiNzAwXCIsXCI5XCI6XCI3MDBpdGFsaWNcIixcIjEwXCI6XCI5MDBcIixcIjExXCI6XCI5MDBpdGFsaWNcIn0sXCJzZWxlY3RlZF92YXJpYW50c1wiOntcIjBcIjpcIjEwMFwifSxcInN1YnNldHNcIjp7XCIwXCI6XCJncmVla1wiLFwiMVwiOlwiY3lyaWxsaWMtZXh0XCIsXCIyXCI6XCJncmVlay1leHRcIixcIjNcIjpcImN5cmlsbGljXCIsXCI0XCI6XCJ2aWV0bmFtZXNlXCIsXCI1XCI6XCJsYXRpblwiLFwiNlwiOlwibGF0aW4tZXh0XCJ9LFwic2VsZWN0ZWRfc3Vic2V0c1wiOntcIjBcIjpcImdyZWVrXCJ9fVwiO30iDQp9";

//The export of the widgets using this plugin http://wordpress.org/plugins/widget-settings-importexport/ - base64 encoded: http://www.base64encode.org/
$demo_widgets = 'W3sib3ZlcmxheS13aWRnZXQtYXJlYS0xIjpbInRpbWJlci1pbWFnZS0yIl0sIm92ZXJsYXktd2lkZ2V0LWFyZWEtMiI6WyJ0ZXh0LTMiLCJ0ZXh0LTQiLCJ0ZXh0LTUiLCJuYXZfbWVudS0zIiwidGV4dC02Il0sIm92ZXJsYXktd2lkZ2V0LWFyZWEtMyI6WyJ0ZXh0LTciLCJuYXZfbWVudS00IiwibmF2X21lbnUtNiIsIm5hdl9tZW51LTciLCJ0ZXh0LTkiXX0seyJ0aW1iZXItaW1hZ2UiOnsiMiI6eyJpbWFnZV9pZCI6MTk2fSwiX211bHRpd2lkZ2V0IjoxfSwidGV4dCI6eyIzIjp7InRpdGxlIjoiIiwidGV4dCI6IkhleSB0aGVyZSxcclxuXHJcbklcdTIwMTltIDxhIGhyZWY9XCIjXCI+QW5zZWwgQWRhbXM8XC9hPiBcdTIwMTQgIGEgZGlnaXRhbCBhcnQgZGlyZWN0b3IgYW5kIHBob3RvZ3JhcGhlciBiYXNlZCBpbiBQYXJpcyAmIE5hbnRlcywgRnJhbmNlLiBcclxuXHJcbklcdTIwMTltIGN1cnJlbnRseSB3b3JraW5nIGFzIG1haW4gcGhvdG9ncmFwaGVyIHdpdGggdGhlIGF3ZXNvbWUgPGEgaHJlZj1cImh0dHBzOlwvXC90d2l0dGVyLmNvbVwvcGl4ZWxncmFkZVwiPkBwaXhlbGdyYWRlPFwvYT4gdGVhbS4gIiwiZmlsdGVyIjp0cnVlfSwiNCI6eyJ0aXRsZSI6IkF2YWlsYWJsZSBmb3IgZnJlZWxhbmNlciB3b3JrIiwidGV4dCI6IjxhIGhyZWY9XCIjXCI+YWRhbUBwaXhlbGdyYWRlLmNvbTxcL2E+IiwiZmlsdGVyIjpmYWxzZX0sIjUiOnsidGl0bGUiOiJJIGNhbiBoZWxwIHlvdSB3aXRoIiwidGV4dCI6IkZhbWlseSBQb3J0cmFpdHNcclxuRW5nYWdlbWVudCBTZXNzaW9uXHJcbk1hdGVybml0eSAmIE5ld2Jvcm5cclxuV2VkZGluZ3MiLCJmaWx0ZXIiOnRydWV9LCI2Ijp7InRpdGxlIjoiIiwidGV4dCI6IkltYWdlIGNyZWRpdHNcclxuQExhdXJlbnQgTml2YWxsZSIsImZpbHRlciI6dHJ1ZX0sIjciOnsidGl0bGUiOiIiLCJ0ZXh0IjoiQ2hlY2sgb3V0IHNvbWUgcmVsZXZhbnQgcGFnZXMgdGhhdCB5b3UgY2FuIGNyZWF0ZSBhbmQgdXNlIHdpdGggVGltYmVyLiIsImZpbHRlciI6ZmFsc2V9LCI5Ijp7InRpdGxlIjoiIiwidGV4dCI6IjxhIGhyZWY9XCJcIj5Ob3RlOjxcL2E+IEFueSBvZiB0aGUgIGFib3ZlIHBhZ2VzIGNhbiBiZSBzZXQgYXMgYSBGcm9udFBhZ2UuIiwiZmlsdGVyIjpmYWxzZX0sIl9tdWx0aXdpZGdldCI6MX0sIm5hdl9tZW51Ijp7IjMiOnsidGl0bGUiOiJZb3UgY2FuIGZpbmQgbWUgb24iLCJuYXZfbWVudSI6OX0sIjQiOnsidGl0bGUiOiJHYWxsZXJpZXMiLCJuYXZfbWVudSI6MTF9LCI2Ijp7InRpdGxlIjoiRmVhdHVyZWQgU2xpZGVyIiwibmF2X21lbnUiOjEyfSwiNyI6eyJ0aXRsZSI6IkdhbGxlcmllcyBBcmNoaXZlIiwibmF2X21lbnUiOjEzfSwiX211bHRpd2lkZ2V0IjoxfX1d';